### ISSUE TITLE
Great work Adam!

### ISSUE THREAD

**Issue by code-r-man** [adamisntdead/gulp-inline-imagesize#1]
Hi Adam, 
it's Nikola from kooba Berlin office. It looks very impressive, I can't wait to try it. Hopefully we will be switching to Gulp soon.

**Comment by adamisntdead** [comment]
Grand, if there's any issues or you make changes, feel free to do a pull request and I can publish, I use GitHub fairly regularly so there's no way I'll miss it.

If I get time over the next few days I'll write some tests too
